service: default
runtime: go
api_version: go1.8
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /_ah/.*
  script: _go_app
  secure: always
  login: admin

nobuild_files:
- vendor

skip_files:
- vendor/.*$
